# Generated by Django 6.0.3 on 2026-03-20 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=1000)),
                ('mail_id', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, default='', max_length=200)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('comments', models.TextField(blank=True, default='')),
                ('season', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_related', to='core.category')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
