# Generated by Django 6.0.3 on 2026-04-04 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['category', 'order'], name='core_anime_categor_6b0858_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'order'], name='core_catego_user_id_4a74f0_idx'),
        ),
    ]
