# Generated by Django 6.0.3 on 2026-03-23 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_mail_id_anime_mal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='mal_id',
        ),
        migrations.AlterField(
            model_name='anime',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_related_data', to='core.category'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='season',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
