# Generated by Django 6.0.3 on 2026-03-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_anime_comments_remove_anime_mal_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='stars',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
