# Generated by Django 6.0.3 on 2026-03-23 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_anime_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='season',
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1)),
                ('total_episodes', models.PositiveIntegerField(default=0)),
                ('watched_episodes', models.PositiveIntegerField(default=0)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season', to='core.anime')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('anime', 'number')},
            },
        ),
    ]
