# Generated by Django 6.0.3 on 2026-03-23 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_anime_season_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='core.anime'),
        ),
    ]
