# Generated by Django 6.0.3 on 2026-03-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_season_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
