# Generated by Django 6.0.3 on 2026-03-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animelist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='mail_id',
            new_name='mal_id',
        ),
    ]
